import type { Address } from "./commute";

// Realistic Pacific Beach / San Diego coastal addresses, pre-geocoded
// (approximate centroids). Keeps demo offline.

export const ADDRESSES: Record<string, Address> = {
  PB_DIAMOND: {
    label: "Diamond Street",
    street: "1245 Diamond Street",
    city: "San Diego",
    state: "CA",
    zip: "92109",
    lat: 32.8093,
    lng: -117.2606,
    neighborhood: "Pacific Beach",
  },
  PB_OPAL: {
    label: "Opal Street",
    street: "956 Opal Street",
    city: "San Diego",
    state: "CA",
    zip: "92109",
    lat: 32.8055,
    lng: -117.2588,
    neighborhood: "Pacific Beach",
  },
  PB_BAYARD: {
    label: "Bayard Street",
    street: "1832 Bayard Street",
    city: "San Diego",
    state: "CA",
    zip: "92109",
    lat: 32.7983,
    lng: -117.2554,
    neighborhood: "Pacific Beach",
  },
  MB_MISSION_BLVD: {
    label: "Mission Boulevard",
    street: "3578 Mission Boulevard",
    city: "San Diego",
    state: "CA",
    zip: "92109",
    lat: 32.7821,
    lng: -117.2538,
    neighborhood: "Mission Beach",
  },
  LJ_NAUTILUS: {
    label: "Nautilus Street",
    street: "412 Nautilus Street",
    city: "La Jolla",
    state: "CA",
    zip: "92037",
    lat: 32.8403,
    lng: -117.2767,
    neighborhood: "La Jolla",
  },
  LJ_FAY: {
    label: "Fay Avenue",
    street: "7642 Fay Avenue",
    city: "La Jolla",
    state: "CA",
    zip: "92037",
    lat: 32.8478,
    lng: -117.2731,
    neighborhood: "La Jolla",
  },
  PL_SUNSET_CLIFFS: {
    label: "Sunset Cliffs Boulevard",
    street: "3271 Sunset Cliffs Boulevard",
    city: "San Diego",
    state: "CA",
    zip: "92106",
    lat: 32.7438,
    lng: -117.2521,
    neighborhood: "Point Loma",
  },
  PL_CATALINA: {
    label: "Catalina Boulevard",
    street: "1502 Catalina Boulevard",
    city: "San Diego",
    state: "CA",
    zip: "92107",
    lat: 32.7299,
    lng: -117.2417,
    neighborhood: "Ocean Beach",
  },
  CLAIREMONT_BURGENER: {
    label: "Burgener Boulevard",
    street: "3145 Burgener Boulevard",
    city: "San Diego",
    state: "CA",
    zip: "92110",
    lat: 32.7724,
    lng: -117.2225,
    neighborhood: "Bay Park",
  },
  CLAIREMONT_BALBOA: {
    label: "Balboa Avenue",
    street: "5021 Balboa Avenue",
    city: "San Diego",
    state: "CA",
    zip: "92117",
    lat: 32.8211,
    lng: -117.1985,
    neighborhood: "Clairemont",
  },
  MISSION_VALLEY_FRIARS: {
    label: "Friars Road",
    street: "2435 Friars Road",
    city: "San Diego",
    state: "CA",
    zip: "92108",
    lat: 32.7706,
    lng: -117.1659,
    neighborhood: "Mission Valley",
  },
  NORTH_PARK_30TH: {
    label: "30th Street",
    street: "2814 30th Street",
    city: "San Diego",
    state: "CA",
    zip: "92104",
    lat: 32.7521,
    lng: -117.1303,
    neighborhood: "North Park",
  },
  DEL_MAR_CAMINO: {
    label: "Camino Del Mar",
    street: "1437 Camino Del Mar",
    city: "Del Mar",
    state: "CA",
    zip: "92014",
    lat: 32.9595,
    lng: -117.2653,
    neighborhood: "Del Mar",
  },
  CARMEL_VALLEY: {
    label: "Del Mar Heights Road",
    street: "3645 Del Mar Heights Road",
    city: "San Diego",
    state: "CA",
    zip: "92130",
    lat: 32.9489,
    lng: -117.2374,
    neighborhood: "Carmel Valley",
  },
  HILLCREST_FOURTH: {
    label: "Fourth Avenue",
    street: "3812 Fourth Avenue",
    city: "San Diego",
    state: "CA",
    zip: "92103",
    lat: 32.7506,
    lng: -117.1606,
    neighborhood: "Hillcrest",
  },
  ENCINITAS_K: {
    label: "K Street",
    street: "212 K Street",
    city: "Encinitas",
    state: "CA",
    zip: "92024",
    lat: 33.0386,
    lng: -117.2913,
    neighborhood: "Encinitas",
  },
};
